# Generated by Django 3.2.7 on 2021-10-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeruser', '0002_alter_appuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
